### ISSUE TITLE
Option to add contact information to a Quest Claim

### ISSUE THREAD

**Issue by pglavin2** [1Hive/quests#301]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
When scheduling a Claim for a Quest, it'd help if you could add contact info (email, Discord, Telegram, etc.) so the Quest creator could get in touch with the Claimer about the Claim and get notified if the Claim is approved.

**Describe alternatives you've considered**
A Claim could also create a forum post in the 1Hive forum, or a thread in Discord where the Creator and Claimer could talk about the submission together.

**Comment by Corantin** [comment]
Yeah, it could definitely help for communication. Maybe we can carry over the contact info with the evidence. However, I think it may be good to have it optional so we keep the possibility of total privacy.
About the discord thread/forum post, it could be really cool for communication but the problem here is that we enforce a user to use the 1hive community tool (join the discord or create a forum account).

**Comment by Corantin** [comment]
For MVP, I included it in the tooltip of Evidence ![image.png](https://images.zenhubusercontent.com/608ac1af9468077230c155b4/6302535c-4062-4fd4-bce1-5e82945a3350)

But I keep this feature request in the backlog to maybe have a separate field in the form to submit contact information
